version: "3.8"

services:
  client:
    container_name: client
    build:
      context: ./client-webapp
      target: serve
    ports:
      - 80:80
    restart: always

  server:
    container_name: server
    build:
      context: ./backend-webapp
      target: build
    ports:
      - 8081:8081
    restart: always
